# Generated by Django 6.1 on 2026-08-13 08:51

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_feature_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='technology_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('original', models.ImageField(upload_to=apps.projects.models.project_original_upload_path)),
                ('rendition_480', models.ImageField(blank=True, upload_to=apps.projects.models.project_rendition_upload_path)),
                ('rendition_960', models.ImageField(blank=True, upload_to=apps.projects.models.project_rendition_upload_path)),
                ('rendition_1600', models.ImageField(blank=True, upload_to=apps.projects.models.project_rendition_upload_path)),
                ('social_1200x630', models.ImageField(blank=True, upload_to=apps.projects.models.project_social_upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_decorative', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('processing_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_images', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='projects.project')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='projects.projectimage')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_projects', to='projects.projectimage'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('is_featured',), name='projects_one_featured_project'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('is_featured', False), ('is_published', True), _connector='OR'), name='projects_featured_requires_published'),
        ),
        migrations.AddConstraint(
            model_name='projectgalleryimage',
            constraint=models.UniqueConstraint(fields=('project', 'image'), name='projects_one_gallery_image'),
        ),
        migrations.AddConstraint(
            model_name='projectgalleryimage',
            constraint=models.UniqueConstraint(fields=('project', 'position'), name='projects_unique_gallery_position'),
        ),
    ]
