# Generated by Django 6.1 on 2026-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_full_feature_list_project_gallery_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('apps', 'Apps'), ('themes', 'Themes'), ('publishing', 'Publishing'), ('features', 'Features'), ('operations', 'Operations')], default='apps', max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'category', 'sort_order'], name='projects_pub_cat_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ('apps', 'themes', 'publishing', 'features', 'operations'))), name='projects_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('slug__in', ('apps', 'themes', 'publishing', 'features', 'operations')), _negated=True), name='projects_slug_not_category'),
        ),
    ]
